# Generated by Django 6.0.3 on 2026-03-28 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('student_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('picture_uri', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=10)),
                ('current_semester', models.IntegerField()),
                ('nrc', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateTimeField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
