# Generated by Django 6.0.3 on 2026-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrances', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrance',
            index=models.Index(fields=['people', 'time'], name='entrance_people_time_idx'),
        ),
    ]
