# Generated by Django 6.0.3 on 2026-04-06 11:24

import django.db.models.deletion
import people.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=people.models.upload_to_unique)),
                ('nrc', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntranceQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_data', models.CharField(editable=False, max_length=500, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='people.people')),
            ],
        ),
    ]
