# Generated by Django 6.0.3 on 2026-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='nrc',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
