# Generated by Django 6.0.3 on 2026-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_people_nrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
